FROM logstash:8.19.9
USER root
COPY --chown=logstash:logstash ./conf/logstash.yml /usr/share/logstash/config/logstash.yml
COPY --chown=logstash:logstash ./conf/pipelines.yml /usr/share/logstash/config/pipelines.yml
COPY --chown=logstash:logstash ./conf/pipeline/logstash.conf /usr/share/logstash/pipeline/logstash.conf

USER logstash
