filebeat.autodiscover:
  providers:
    - type: docker
      host: "unix:///var/run/docker.sock"
      templates:
        - condition:
            contains:
              docker.container.image: "grafanahost"
          config:
            - type: container
              paths:
                - "/var/lib/docker/containers/${data.docker.container.id}/*.log"

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
